### ISSUE TITLE
V2R4

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#268]
https://vaulted.io/library/disa-stigs-srgs/RHEL_7_STIG?version=V2R3&compareto=V2R4

- [x] new rule for ctrl-alt-del in gui (#266)
- [x] removed `net.ipv4.tcp_invalid_ratelimit` (#274)
- [x] rpm -Va must check Mode, User, Group (no change required)
- [x] rpm -Va --noconfig (#279)
- [x] updated faillock requirements (no change required)
- [x] proper usb-storage remediation (#272)
- [x] GUI portion removed from RHEL-07-020230
- [x] fixed selection of dotfiles to skip CWD and parent (`.` and `..`) (no change required, but RHEL-07-020710 still not implemented)
- [x] 75->25 audit space (#228)
- [x] b32 and b64 required everywhere (no change required)
- [x] /etc/security/limits.d/*.conf is acceptable (no change required)
- [x] proper dccp blacklist (#278)

**Comment by jamescassell** [comment]
PRs now open for all V2R4 items.

**Comment by jamescassell** [comment]
All V2R4 items have been corrected.  I've also opened a PR to update the README to reflect V2R4: (#280)
